spring:
  application:
    name: verbamind
    profiles:
      active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

server:
  port: 8080
  error:
    include-message: always

management:
  endpoints:
    web:
      expose:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.verbamind: DEBUG
    org.springframework.web: INFO